root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server && go build -o ./tmp/agent ./cmd/agent"
  full_bin = "sh -c './tmp/server & ./tmp/agent & wait'"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 1000

[log]
  time = true
